name = "JSServe"
uuid = "824d6782-a2ef-11e9-3a09-e5662e0c26f9"
authors = ["SimonDanisch <sdanisch@gmail.com>"]
version = "1.2.9"

[deps]
Base64 = "2a0f44e3-6c83-55bd-87e4-b1978d98bd5f"
CodecZlib = "944b1d66-785c-5afd-91f1-9de20f533193"
Colors = "5ae59095-9a9b-59fe-a467-6f913c188581"
HTTP = "cd3eb016-35fb-5094-929b-558a96fad6f3"
Hyperscript = "47d2ed2b-36de-50cf-bf87-49c2cf4b8b91"
JSON3 = "0f8b85d8-7281-11e9-16c2-39a750bddbf1"
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
Markdown = "d6f4376e-aef5-505a-96c1-9c027394607a"
MsgPack = "99f44e22-a591-53d1-9472-aa23ef4bd671"
Observables = "510215fc-4207-5dde-b226-833fc4488ee2"
RelocatableFolders = "05181044-ff0b-4ac5-8273-598c1e38db00"
SHA = "ea8e919c-243c-51af-8825-aaa63cd721ce"
Sockets = "6462fe0b-24de-5631-8697-dd941f90decc"
Tables = "bd369af6-aec1-5ad0-b16a-f7cc5008161c"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"
UUIDs = "cf7118a7-6976-5b1a-9a39-7adc72f591a4"
WebSockets = "104b5d7c-a370-577a-8038-80a2059c5097"
WidgetsBase = "eead4739-05f7-45a1-878c-cee36b57321c"

[compat]
CodecZlib = "0.7"
Colors = "0.12"
HTTP = "0.8, 0.9"
Hyperscript = "0.0.3, 0.0.4"
JSON3 = "1.0"
MsgPack = "1.1.0"
Observables = "0.5.1"
RelocatableFolders = "0.1, 0.2, 1"
Tables = "1"
WebSockets = "1.5"
WidgetsBase = "0.1"
julia = "1.3"

[extras]
Electron = "a1bb12fb-d4d1-54b4-b10a-ee7951ef7ad3"
ElectronDisplay = "d872a56f-244b-5cc9-b574-2017b5b909a8"
Pkg = "44cfe95a-1eb2-52ea-b672-e2afdf69b78f"
Random = "9a3f8284-a2c9-5f02-9a11-845980a1fd5c"
URIParser = "30578b45-9adc-5946-b283-645ec420af67"

[targets]
test = ["URIParser", "Pkg", "Electron", "Random", "ElectronDisplay"]
