name = "JSServe"
uuid = "824d6782-a2ef-11e9-3a09-e5662e0c26f9"
authors = ["SimonDanisch <sdanisch@gmail.com>"]
version = "0.4.0"

[deps]
AssetRegistry = "bf4720bc-e11a-5d0c-854e-bdca1663c893"
Base64 = "2a0f44e3-6c83-55bd-87e4-b1978d98bd5f"
ElectronTests = "fa9e6d27-338f-4c48-a526-3b082c2df35e"
HTTP = "cd3eb016-35fb-5094-929b-558a96fad6f3"
Hyperscript = "47d2ed2b-36de-50cf-bf87-49c2cf4b8b91"
JSON3 = "0f8b85d8-7281-11e9-16c2-39a750bddbf1"
Markdown = "d6f4376e-aef5-505a-96c1-9c027394607a"
MsgPack = "99f44e22-a591-53d1-9472-aa23ef4bd671"
Observables = "510215fc-4207-5dde-b226-833fc4488ee2"
Sockets = "6462fe0b-24de-5631-8697-dd941f90decc"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"
UUIDs = "cf7118a7-6976-5b1a-9a39-7adc72f591a4"
WebSockets = "104b5d7c-a370-577a-8038-80a2059c5097"
WidgetsBase = "eead4739-05f7-45a1-878c-cee36b57321c"

[compat]
AssetRegistry = "0.1"
HTTP = "=0.8.8"
Hyperscript = "0.0.3"
JSON3 = "0.1, 1.0"
MsgPack = "1.1.0"
Observables = "0.2.3, 0.3"
WebSockets = "1.5"
WidgetsBase = "0.1"
julia = "1.3"

[extras]
AbstractPlotting = "537997a7-5e4e-5d89-9595-2241ea00577e"
Electron = "a1bb12fb-d4d1-54b4-b10a-ee7951ef7ad3"
ElectronDisplay = "d872a56f-244b-5cc9-b574-2017b5b909a8"
ElectronTests = "fa9e6d27-338f-4c48-a526-3b082c2df35e"
ImageTransformations = "02fcd773-0e25-5acc-982a-7f6622650795"
Random = "9a3f8284-a2c9-5f02-9a11-845980a1fd5c"
URIParser = "30578b45-9adc-5946-b283-645ec420af67"
WGLMakie = "276b4fcb-3e11-5398-bf8b-a0c2d153d008"

[targets]
test = ["URIParser", "Electron", "Random", "ElectronDisplay", "WGLMakie", "AbstractPlotting", "ImageTransformations", "ElectronTests"]
